name: echo_flutter
description: Echo-style music player for Android + iOS
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.50
  provider: ^6.0.5
  file_picker: ^5.3.2
  path_provider: ^2.0.16
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
    
